### ISSUE TITLE
Can't get xcimporter to work

### ISSUE THREAD

**Issue by tdudgeon** [xchem/fragalysis-api#53]
I'm working on using xcimporter to format data for Janssen and can't get it working.

The first problem is that there seems to be a missing import which I fixed in this PR: https://github.com/xchem/fragalysis-api/pull/52

With that fixed the script runs but gives an error. 
My inputs are as follows:
```
data
├── Mpro-x0072.pdb
└── Mpro-x0072.txt
```

It was executed like this:
```
python -m fragalysis_api.xcimporter.xcimporter -i data -o out -m -t Mpro
```

The output looks like this:
```
Making output directories
Monomerizing input structures
data/Mpro-x0072.pdb
[' LIG A1101']
 PyMOL not running, entering library mode (experimental)
['out/mono/Mpro-x0072_A_mono.pdb']

... whole lot of PDB file 

out/mono/Mpro-x0072_A_smiles.txt
[None]
Aligning protein structures
[None]
Identifying ligands
out/Mpro/aligned
/home/timbo/miniconda3/envs/fragalysis-api-dependencies/lib/python3.8/site-packages/pypdb/pypdb.py:449: UserWarning: Retrieval failed, returning None
  warnings.warn("Retrieval failed, returning None")
Warning: No smiles file: Mpro-x0072_0A
Files are now in a fragalysis friendly format!
Traceback (most recent call last):
  File "/home/timbo/miniconda3/envs/fragalysis-api-dependencies/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/timbo/miniconda3/envs/fragalysis-api-dependencies/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/timbo/github/xchem/fragalysis-api/fragalysis_api/xcimporter/xcimporter.py", line 176, in <module>
    fix_pdb.write(target_file.split('-')[1]+'\n')
IndexError: list index out of range
```

Some output files are present but I think some are missing (the `Mpro/crystallographic` directory?):
```
out
├── mono
│   └── Mpro-x0072_A.pdb
├── Mpro
│   └── aligned
│       ├── Mpro-x0072_0A
│       │   ├── Mpro-x0072_0A_apo-desolv.pdb
│       │   ├── Mpro-x0072_0A_apo.pdb
│       │   ├── Mpro-x0072_0A_apo-solv.pdb
│       │   ├── Mpro-x0072_0A_bound.pdb
│       │   ├── Mpro-x0072_0A_meta.csv
│       │   ├── Mpro-x0072_0A.mol
│       │   ├── Mpro-x0072_0A.pdb
│       │   └── Mpro-x0072_0A.sdf
│       └── pdb_file_failures.txt
└── tmp
    └── Mpro-x0072_A_bound.pdb
```

**Comment by reskyner** [comment]
The crystallographic directory is manually created at time of upload, and is not needed by the loader. The loader looks in Mpro/aligned to decide what to process. Anything you add a level up has no functional purpose. 

Send me the example files and I might be able to work out what's going on...

You need other files for the loader too. Do you have examples?

**Comment by reskyner** [comment]
Ah - my instructions are wrong. The smiles file should be <whatever>_smiles.txt
